### ISSUE TITLE
Interested to use ChallengeEnvironment as a case study in teaching RL

### ISSUE THREAD

**Issue by mirfanud** [IBM/ushiriki-policy-engine-library#13]
Hello

I would like to use the ChallengeEnvironment for Reinforcement Learning class at Kohat University of Science and Technology from Dec-2019 to June-2020.

**Comment by slremy** [comment]
We'd love to support this use of the library.

**Comment by slremy** [comment]
Hello! Just checking in. Was this activity successful? We've actually made some extensions which might make things a little simpler to use by incorporating a gym environment around the challenge environment. Please let us know!

**Comment by mirfanud** [comment]
Hello! Thanks for asking. Yes we had a good time to experiment with the environment. One group managed to write a paper on some RL algorithm working in the challenge environment. Will keep you updated when there is more progress.

**Comment by slremy** [comment]
Awesome! Will close this issue, but hope that you can still post a link to that paper so the community can learn.
